### PR TITLE
show all-long package name; storage access; backup and apply enabled state

### PR DESCRIPTION
**Pull request by NewBugger**
notice: directory change available only on Android 10 and below, due to app-specific access is denied on Android 11.

### CODE REVIEW

**Comment by lihenggui** [comment]
Do you mean the storage API change in Android 11?

**Comment by NewBugger** [comment]
yes. DO NOT use File operation under target 30 now, and target 29 is fine.

**Comment by lihenggui** [comment]
So you want to make Blocker adapt to Android 11 in advance, is it correct?

**Comment by NewBugger** [comment]
this pr is for export (File operation) fix on target 29 + Android 10 system. look commits for detail.

**Comment by NewBugger** [comment]
simplified: Blocker `export rule` cannot work on Android 11.

**Comment by lihenggui** [comment]
Ok got it

**Comment by NewBugger** [comment]
export will works fine on  Android 10 and below, with those latest prs.

**Comment by lihenggui** [comment]
@NewBugger I will test tonight. Recently I add requestLegacyExternalStorage=true to make sure export function works.

**Comment by NewBugger** [comment]
> @NewBugger I will test tonight. Recently I add requestLegacyExternalStorage=true to make sure export function works.

it's not really really recommended to manifest. for Android 11, you need to use newer storage practices. or i can do this later.

**Comment by lihenggui** [comment]
Yes, as this API mentioned this function is just a temporary solution. I will adapt Blocker to scoped storage soon, or if you have time you could push PR. Thanks for your effort.

**Comment by NewBugger** [comment]
if necessary, use `target 28` rather than `requestLegacyExternalStorage`

**Comment by lihenggui** [comment]
> if necessary, use `target 28` rather than `requestLegacyExternalStorage`

What's your concern about it?

**Comment by NewBugger** [comment]
indeed performance and security. when comparied, downgrade its target api will affect nothing.

**Comment by lihenggui** [comment]
Thanks, I got it.

**Comment by lihenggui** [comment]
Why do you want to save enabled state? Do you want to restore all components' state?

**Comment by NewBugger** [comment]
yes, it's a useful commit.

**Comment by lihenggui** [comment]
I need to modify this commit. In API 29 export function didn't work because of the `android.permission.WRITE_EXTERNAL_STORAGE` gets removed.

**Comment by NewBugger** [comment]
so i wrote it `android:maxSdkVersion="28"`. strongly recommended downgrade target api rather than requestLegacyStorage.

**Comment by NewBugger** [comment]
here provide you a dirty usage: access external storage using ROOT command (mainly for api 29). Blocker is ROOT required app (mostly ignores shizuku mode), so nothing need change. and recommended to add a option for this dirty usage.

**Pull request merged**
